# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MergeCSV
                                 A QGIS plugin
 Merges data from a comma-separated-values file (.csv) to an existing layer with the same structure.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-27
        copyright            : (C) 2022 by labMGF
        email                : federica.gaspari@polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MergeCSV class from file MergeCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .merge_csv import MergeCSV
    return MergeCSV(iface)
